### ISSUE TITLE
cluster: helm: Fix Helm repo installation and refresh

### ISSUE THREAD

**Issue by pozgo** [iac-io/myiac#37]

**Comment by pozgo** [comment]
Make sure wait 10s is moved to `helm` function instead of main func 
https://github.com/iac-io/myiac/blob/d71cffd5555fc68303e048a7c936c2b05b755d99/internal/cluster/cluster.go#L68

**Comment by dfernandezm** [comment]
Also, no need to use `install-helm.sh` and the surrounding setup. Originally this was setup with Helm 2. The syntax to install/upgrade is different too. Already tracking upgrade through SDK in #26 , but can consider just a minor commandline change.

About that 10s wait, some time is needed after the cluster is up (terraform apply finishes) and actioning it (install helm). With v3 this goes away.

Proposal:

- Refactor `helmDeployer` / `helm.go` / `deploy.go` so it works with Helm v3 (need issue created) - estimate 1 day for it to work with v3
- Future inclusion of wrapper which removes the need for the helm binary (#26) - need investigation for assessing estimate
