### ISSUE TITLE
cicd: Add build and store artefact

### ISSUE THREAD

**Issue by pozgo** [iac-io/myiac#58]
We should store build binary after build successfull

**Comment by dfernandezm** [comment]
For artifacts in general: 
- https://itnext.io/github-use-actions-to-publish-artifacts-e42fc76a8a63
- Cross build https://github.com/marketplace/actions/go-cross-build
- Step by step with codecov, publish release, https://brunopaz.dev/blog/building-a-basic-ci-cd-pipeline-for-a-golang-application-using-github-actions
